### PR TITLE
feat: clean code and bump dependencies

### PR DESCRIPTION
**Pull request by fitbeard**
- Update usage documentation
- Bump dependencies
- Remove unnecessary function `secretTokenRenew` (application credentials are not renewable)
- Use milliseconds for name formatting. This is a default for Vault SDK and every other official secret engine: https://github.com/hashicorp/vault/blob/03d2be4cb943115af1bcddacf5b8d79f3ec7c210/sdk/helper/template/funcs.go#L19
- Add description with handy info and timestamp for better filtering

### CODE REVIEW

**Comment by mnaser** [comment]
@fitbeard do you think you might have time to flip this over to github actions?  if not i can carve out sometime for that.

**Comment by fitbeard** [comment]
@mnaser sure. For the start what we need? golang linter, test build? Multi arch releaser?

**Comment by mnaser** [comment]
That seems more than enough!  I don't know if we run unit tests now but it would be good to run go test anyways and build/multi arch release and linters is more than enough

**Comment by fitbeard** [comment]
@mnaser it's ready for testing. You need to add some `secrets.GITHUB_TOKEN` to make releases possible.

**Pull request merged**
